# Initiation à Pandas - Les DataFrames -

Email : <a href='mailto:madani.a@ucd.ac.ma'>madani.a@ucd.ac.ma</a>
<img src='images/pandas.jpg'>

## Introduction
<p>
Pandas est une librairie python qui permet de manipuler facilement des données à analyser :
<ul>
<li>manipuler des tableaux de données avec des étiquettes de variables (colonnes) et d'individus (lignes).
<li>ces tableaux sont appelés DataFrames.
<li>on peut facilement lire et écrire ces dataframes à partir ou vers un fichier tabulé.
<li>on peut faciler tracer des graphes à partir de ces DataFrames grâce à matplotlib.
</ul>
</p>
<p>
Pour utiliser pandas : <strong>import pandas</strong>
</p>

## DataFrames

<p>
La structure de données clé dans Pandas est l'objet <strong>DataFrame</strong>. Un DataFrame est essentiellement une structure de données tabulaire, avec des lignes et des colonnes. Les lignes ont un index spécifique pour y accéder, qui peut avoir n'importe quel nom ou n'importe quelle valeur. Dans Pandas, les colonnes sont appelées <strong>Series</strong>, un type spécial de données, qui consiste essentiellement en une liste de plusieurs valeurs, où chaque valeur a un index. Par conséquent, la structure de données DataFrame peut être considérée comme une feuille de calcul (qui ressemble à une feuille Excel), mais elle est beaucoup plus flexible.
</p>

## Créer un nouveau DataFrame

<p>
Pour comprendre comment cela fonctionne, voyons comment créer un objet DataFrame de différentes manières :
</p>
<p>
<b>Création d'un dataFrame vide</b>
</p>

In [1]:
import pandas as pd
df = pd.DataFrame()
print (df)

Empty DataFrame
Columns: []
Index: []

<b>Création d'un DataFrame à partir d'une liste</b>

In [2]:
import pandas as pd
data = [10,20,30,40,50]
df = pd.DataFrame(data)
print(df)

    0
0  10
1  20
2  30
3  40
4  50

<b>Création d'un DataFrame à partir de listes</b>

In [2]:
import pandas as pd
data = [['Alex',10],['Bob',12],['Clarke',13]]
df = pd.DataFrame(data)
print(df)

        0   1
0    Alex  10
1     Bob  12
2  Clarke  13

In [1]:
import pandas as pd
data = [['Alex',10],['Bob',12],['Clarke',13]]
df = pd.DataFrame(data,columns=['Name','Age'],dtype=float)
print(df)

     Name   Age
0    Alex  10.0
1     Bob  12.0
2  Clarke  13.0

In [2]:
df['Name']

0      Alex
1       Bob
2    Clarke
Name: Name, dtype: object

<b> Création d'un DataFrame à partir d'un dictionnaire</b>

<p>
Dans cet exemple, nous utilisons le constructeur d'objet DataFrame pandas avec un dictionnaire de listes Python en tant qu'argument. <i><b>La clé de chaque entrée dans le dictionnaire est le nom de la colonne et les listes sont leurs valeurs.</b></i>
</p>

In [4]:
import pandas as pd
data = {'Années': [2010, 2011, 2012, 2010, 2011, 2012, 2010, 2011, 2012],
        'Equipes': ['FCBarcelona', 'FCBarcelona', 'FCBarcelona', 'RMadrid', 'RMadrid', 'RMadrid', 'ValenciaCF',
                 'ValenciaCF', 'ValenciaCF'],
        'matches gagnés':   [30, 28, 32, 29, 32, 26, 21, 17, 19],
        'matches égalités':  [6, 7, 4, 5, 4, 7, 8, 10, 8],
        'matches perdus': [2, 3, 2, 4, 2, 5, 9, 11, 11]
        }
equipes = pd.DataFrame(data)#, columns = ['Année', 'Equipes', 'matches gagnés', 'matches égalités', 'matches perdus'])
equipes

   Années      Equipes  matches gagnés  matches égalités  matches perdus
0    2010  FCBarcelona              30                 6               2
1    2011  FCBarcelona              28                 7               3
2    2012  FCBarcelona              32                 4               2
3    2010      RMadrid              29                 5               4
4    2011      RMadrid              32                 4               2
5    2012      RMadrid              26                 7               5
6    2010   ValenciaCF              21                 8               9
7    2011   ValenciaCF              17                10              11
8    2012   ValenciaCF              19                 8              11

<p>
Le résultat est une table où chaque entrée du dictionnaire est une colonne dans l'objet DataFrame. L'index de chaque ligne est créé automatiquement en prenant la position de ses éléments dans les listes d'entrée, en commençant par 0. Bien qu'il soit très facile de créer des DataFrames à partir de zéro (from scratch), la plupart du temps on est amené à importer des données dans une structure DataFrame.
</p>

## Lecture de données tabulaires dans pandas

<p>
La façon de lire les fichiers CSV dans Pandas consiste à utiliser la méthode <strong>read_csv</strong>. En plus du nom du fichier, nous ajoutons l'argument clé <strong>na_values</strong> à cette méthode avec le caractère représentant les "données non disponibles" dans le fichier. Normalement, les fichiers CSV ont un en-tête avec les noms des colonnes. Si tel est le cas, nous pouvons utiliser le paramètre <strong>usecols</strong> pour sélectionner les colonnes du fichier qui seront utilisées.
</p>

In [8]:
import pandas as pd
# remarquez que le fichier se trouve dans le dossier 'datasets' du repository
titanic = pd.read_csv('datasets/titanic.csv')
titanic.head()

,PassengerId,Survived,Pclass,Name,Sex,Age,SibSp,Parch,Ticket,Fare,Cabin,Embarked
0,1,0,3,"Braund, Mr. Owen Harris",male,22.0,1,0,A/5 21171,7.2500,NaN,S
1,2,1,1,"Cumings, Mrs. John Bradley (Florence Briggs Th...",female,38.0,1,0,PC 17599,71.2833,C85,C
2,3,1,3,"Heikkinen, Miss. Laina",female,26.0,0,0,STON/O2. 3101282,7.9250,NaN,S
3,4,1,1,"Futrelle, Mrs. Jacques Heath (Lily May Peel)",female,35.0,1,0,113803,53.1000,C123,S
4,5,0,3,"Allen, Mr. William Henry",male,35.0,0,0,373450,8.0500,NaN,S

<p>
En plus de la méthode <strong>read_csv</strong>, Pandas fournit aussi des fonctions pour lire des fichiers avec des formats comme Excel, HDF5, des fichiers tabulaires ou même le contenu du presse-papiers (<strong>read_excel ()</strong>, <strong>read_hdf ()</strong>, <strong>read_table ()</strong>, <strong>read_clipboard ()</strong>) . Quelle que soit la fonction utilisée, le résultat de la lecture d'un fichier est stocké en tant qu'objet DataFrame.
</p>

## Affichage des données
<p>
Pour voir à quoi ressemblent les données, nous pouvons utiliser la méthode <strong>head ()</strong>, qui montre seulement les cinq premières lignes. Si nous passons un nombre en argument de cette méthode, ce sera le nombre des premières lignes affichées.
</p>

In [9]:
# Affichage des 5 premières lignes
titanic.head() #Equivalent à education.head(5)

,PassengerId,Survived,Pclass,Name,Sex,Age,SibSp,Parch,Ticket,Fare,Cabin,Embarked
0,1,0,3,"Braund, Mr. Owen Harris",male,22.0,1,0,A/5 21171,7.2500,NaN,S
1,2,1,1,"Cumings, Mrs. John Bradley (Florence Briggs Th...",female,38.0,1,0,PC 17599,71.2833,C85,C
2,3,1,3,"Heikkinen, Miss. Laina",female,26.0,0,0,STON/O2. 3101282,7.9250,NaN,S
3,4,1,1,"Futrelle, Mrs. Jacques Heath (Lily May Peel)",female,35.0,1,0,113803,53.1000,C123,S
4,5,0,3,"Allen, Mr. William Henry",male,35.0,0,0,373450,8.0500,NaN,S

In [10]:
# Affichage des 10 premières lignes
titanic.head(10)

,PassengerId,Survived,Pclass,Name,Sex,Age,SibSp,Parch,Ticket,Fare,Cabin,Embarked
0,1,0,3,"Braund, Mr. Owen Harris",male,22.0,1,0,A/5 21171,7.2500,NaN,S
1,2,1,1,"Cumings, Mrs. John Bradley (Florence Briggs Th...",female,38.0,1,0,PC 17599,71.2833,C85,C
2,3,1,3,"Heikkinen, Miss. Laina",female,26.0,0,0,STON/O2. 3101282,7.9250,NaN,S
3,4,1,1,"Futrelle, Mrs. Jacques Heath (Lily May Peel)",female,35.0,1,0,113803,53.1000,C123,S
4,5,0,3,"Allen, Mr. William Henry",male,35.0,0,0,373450,8.0500,NaN,S
5,6,0,3,"Moran, Mr. James",male,NaN,0,0,330877,8.4583,NaN,Q
6,7,0,1,"McCarthy, Mr. Timothy J",male,54.0,0,0,17463,51.8625,E46,S
7,8,0,3,"Palsson, Master. Gosta Leonard",male,2.0,3,1,349909,21.0750,NaN,S
8,9,1,3,"Johnson, Mrs. Oscar W (Elisabeth Vilhelmina Berg)",female,27.0,0,2,347742,11.1333,NaN,S
9,10,1,2,"Nasser, Mrs. Nicholas (Adele Achem)",female,14.0,1,0,237736,30.0708,NaN,C

De même, il existe la méthode <strong>tail ()</strong>, qui retourne les cinq dernières lignes par défaut.

In [11]:
titanic.tail()

,PassengerId,Survived,Pclass,Name,Sex,Age,SibSp,Parch,Ticket,Fare,Cabin,Embarked
886,887,0,2,"Montvila, Rev. Juozas",male,27.0,0,0,211536,13.00,NaN,S
887,888,1,1,"Graham, Miss. Margaret Edith",female,19.0,0,0,112053,30.00,B42,S
888,889,0,3,"Johnston, Miss. Catherine Helen ""Carrie""",female,NaN,1,2,W./C. 6607,23.45,NaN,S
889,890,1,1,"Behr, Mr. Karl Howell",male,26.0,0,0,111369,30.00,C148,C
890,891,0,3,"Dooley, Mr. Patrick",male,32.0,0,0,370376,7.75,NaN,Q

In [12]:
titanic.tail(3)

,PassengerId,Survived,Pclass,Name,Sex,Age,SibSp,Parch,Ticket,Fare,Cabin,Embarked
888,889,0,3,"Johnston, Miss. Catherine Helen ""Carrie""",female,NaN,1,2,W./C. 6607,23.45,NaN,S
889,890,1,1,"Behr, Mr. Karl Howell",male,26.0,0,0,111369,30.00,C148,C
890,891,0,3,"Dooley, Mr. Patrick",male,32.0,0,0,370376,7.75,NaN,Q

<p>
Si nous voulons connaître les noms des colonnes ou les noms des index, nous pouvons utiliser les attributs <strong>columns</strong> et <strong>index</strong> de DataFrame. Les noms des colonnes ou des index peuvent être modifiés en affectant une nouvelle liste de la même longueur à ces attributs.
</p>

In [13]:
titanic.columns

Index(['PassengerId', 'Survived', 'Pclass', 'Name', 'Sex', 'Age', 'SibSp',
       'Parch', 'Ticket', 'Fare', 'Cabin', 'Embarked'],
      dtype='object')

In [14]:
titanic.index

RangeIndex(start=0, stop=891, step=1)

<p>
Les valeurs d'un DataFrame peuvent être récupérées en tant que tableau Python en appelant son attribut values.
</p>

In [15]:
titanic.values

array([[1, 0, 3, ..., 7.25, nan, 'S'],
       [2, 1, 1, ..., 71.2833, 'C85', 'C'],
       [3, 1, 3, ..., 7.925, nan, 'S'],
       ...,
       [889, 0, 3, ..., 23.45, nan, 'S'],
       [890, 1, 1, ..., 30.0, 'C148', 'C'],
       [891, 0, 3, ..., 7.75, nan, 'Q']], dtype=object)

<p>
Si nous voulons simplement des informations statistiques rapides sur toutes les colonnes numériques d'un DataFrame, nous pouvons utiliser la fonction <strong>describe ()</strong>. Le résultat de la fonction montre le nombre, la moyenne, l'écart type, le minimum et le maximum, et les centiles, par défaut, les 25e, 50e et 75e, pour toutes les valeurs de chaque colonne (chaque série).
</p>

In [16]:
titanic.describe()

,PassengerId,Survived,Pclass,Age,SibSp,Parch,Fare
count,891.000000,891.000000,891.000000,714.000000,891.000000,891.000000,891.000000
mean,446.000000,0.383838,2.308642,29.699118,0.523008,0.381594,32.204208
std,257.353842,0.486592,0.836071,14.526497,1.102743,0.806057,49.693429
min,1.000000,0.000000,1.000000,0.420000,0.000000,0.000000,0.000000
25%,223.500000,0.000000,2.000000,20.125000,0.000000,0.000000,7.910400
50%,446.000000,0.000000,3.000000,28.000000,0.000000,0.000000,14.454200
75%,668.500000,1.000000,3.000000,38.000000,1.000000,0.000000,31.000000
max,891.000000,1.000000,3.000000,80.000000,8.000000,6.000000,512.329200

## La sélection

<p>
Si nous voulons sélectionner un sous-ensemble de données à partir d'un DataFrame, il est nécessaire d'indiquer ce sous-ensemble à l'aide de crochets [] après le DataFrame. Le sous-ensemble peut être spécifié de plusieurs façons. Si nous voulons sélectionner seulement une colonne d'un DataFrame, nous avons  besoin seulement de mettre son nom entre les crochets. Le résultat sera une série, et non pas un DataFrame, car une seule colonne est récupérée.
</p>

In [18]:
# Sélectionner la colonne 'Value' du DataFrame
titanic['Pclass'].head()

0    3
1    1
2    3
3    1
4    3
Name: Pclass, dtype: int64

<p>
Si nous voulons sélectionner un sous-ensemble de lignes d'un DataFrame, nous pouvons le faire en indiquant une plage de lignes entre crochets et séparées par <strong>":"</strong>.
</p>
<p>
L'instruction suivante renvoie la tranche de lignes entre la 10ème à la 13ème position. Notez que la tranche n'utilise pas les étiquettes d'index comme références, mais la position. Dans ce cas, les étiquettes des lignes coïncident simplement avec la position des lignes.
</p>

In [19]:
titanic[10:14]

,PassengerId,Survived,Pclass,Name,Sex,Age,SibSp,Parch,Ticket,Fare,Cabin,Embarked
10,11,1,3,"Sandstrom, Miss. Marguerite Rut",female,4.0,1,1,PP 9549,16.700,G6,S
11,12,1,1,"Bonnell, Miss. Elizabeth",female,58.0,0,0,113783,26.550,C103,S
12,13,0,3,"Saundercock, Mr. William Henry",male,20.0,0,0,A/5. 2151,8.050,NaN,S
13,14,0,3,"Andersson, Mr. Anders Johan",male,39.0,1,5,347082,31.275,NaN,S

<p>
Si nous voulons sélectionner un sous-ensemble de colonnes et de lignes en utilisant les étiquettes comme références au lieu des positions, nous pouvons utiliser l'indexation <strong>loc</strong> :
</p>
<p>
L'instruction suivante renvoie toutes les lignes ayant :
<ul>
<li>les index spécifiés avant la virgule
<li>les colonnes spécifiées en tant que liste après la virgule
</ul>
<p>
Dans ce cas, <strong>loc</strong> ne renvoie pas les 90<sup>e</sup> à 94<sup>e</sup> lignes, mais renvoie toutes les lignes entre la ligne étiquetée 90 et la ligne étiquetée 94.
</p>

In [21]:
titanic.loc[90:94, ['Survived', 'Pclass']]

    Survived  Pclass
90         0       3
91         0       3
92         0       1
93         0       3
94         0       3

In [22]:
titanic[['Survived', 'Pclass']].tail()

     Survived  Pclass
886         0       2
887         1       1
888         0       3
889         1       1
890         0       3

## Filtrer les données
<p>
Une autre façon de sélectionner un sous-ensemble de données consiste à appliquer une condition booléenne. Cette condition est communément appelée un filtre. Par exemple, si nous voulons sélectionner seulement les 5 premières lignes ayant la colonne 'Value' inférieures ou égales à 6.5, nous pouvons le faire comme ceci :
</p>

In [24]:
titanic[titanic['Age'] <= 40].head()

,PassengerId,Survived,Pclass,Name,Sex,Age,SibSp,Parch,Ticket,Fare,Cabin,Embarked
0,1,0,3,"Braund, Mr. Owen Harris",male,22.0,1,0,A/5 21171,7.2500,NaN,S
1,2,1,1,"Cumings, Mrs. John Bradley (Florence Briggs Th...",female,38.0,1,0,PC 17599,71.2833,C85,C
2,3,1,3,"Heikkinen, Miss. Laina",female,26.0,0,0,STON/O2. 3101282,7.9250,NaN,S
3,4,1,1,"Futrelle, Mrs. Jacques Heath (Lily May Peel)",female,35.0,1,0,113803,53.1000,C123,S
4,5,0,3,"Allen, Mr. William Henry",male,35.0,0,0,373450,8.0500,NaN,S

<p>
La condition booléenne renvoie <strong>True</strong> ou <strong>False</strong> pour chaque ligne. Les lignes qui correspondent à la valeur True seront sélectionnées.
</p>
<p>
Dans l'exemple précédent, l'opération booléenne <strong>education ['Value'] &lt;= 6.5</strong> produit un masque booléen. Lorsqu'un élément de la colonne 'Value' est inférieur ou égal à 6.5, la valeur correspondante dans le masque est définie par True, sinon elle est définie par False.
</p>
<p>
Bien sûr, les opérateurs booléens habituels peuvent être utilisés pour le filtrage :
</p>
<table border="1">
<tr>
<td>&lt;</td><td>inférieur à</td>
</tr>
<tr>
<td> &lt;=</td><td>inférieur ou égal à</td>
</tr>
<tr>
<td>&gt;</td><td>supérieur à</td>
</tr>
<tr>
<td>&gt;=</td><td>supérieur ou égal à</td>
</tr>
<tr>
<td>==</td><td>égal à</td>
</tr>
<tr>
<td>!=</td><td>différent de</td>
</tr>
</table>

## Filtrage des valeurs manquantes
<p>
Pandas utilise la valeur spéciale <strong>NaN</strong> (Not a Number, pas un nombre) pour représenter les valeurs manquantes. Une caractéristique subtile des valeurs NaN est que deux NaN ne sont jamais égaux. Pour cette raison, le seul moyen sûr de savoir si une valeur est manquante dans un DataFrame est d'utiliser la fonction <strong>isnull()</strong> :
</p>

In [25]:
titanic[titanic['Age'].isnull()].head()

,PassengerId,Survived,Pclass,Name,Sex,Age,SibSp,Parch,Ticket,Fare,Cabin,Embarked
5,6,0,3,"Moran, Mr. James",male,NaN,0,0,330877,8.4583,NaN,Q
17,18,1,2,"Williams, Mr. Charles Eugene",male,NaN,0,0,244373,13.0000,NaN,S
19,20,1,3,"Masselmani, Mrs. Fatima",female,NaN,0,0,2649,7.2250,NaN,C
26,27,0,3,"Emir, Mr. Farred Chehab",male,NaN,0,0,2631,7.2250,NaN,C
28,29,1,3,"O'Dwyer, Miss. Ellen ""Nellie""",female,NaN,0,0,330959,7.8792,NaN,Q

## Manipulation des données

<p>
Une fois que nous savons comment sélectionner les données souhaitées, la prochaine étape est de savoir comment manipuler les données. L'une des choses les plus simples que nous puissions faire est de manipuler des colonnes ou des lignes en utilisant des fonctions d'agrégation. La liste suivante montre les fonctions d'agrégation les plus courantes :
</p>

<table>
<tr>
<td>Fonction</td><td>Description</td>
</tr>
<tr>
<td>count()</td><td>Nombres d'observations non nulles</td>
</tr>
<tr>
<td>sum()</td><td>La somme des valeurs</td>
</tr>
<tr>
<td>mean()</td><td>La moyenne des valeurs</td>
</tr>
<tr>
<td>median()</td><td>La médiane arithmétique des valeurs</td>
</tr>
<tr>
<td>min()</td><td>Le minimum de plusieurs valeurs</td>
</tr>
<tr>
<td>max()</td><td>Le maximum de plusieurs valeurs</td>
</tr>
<tr>
<td>prod()</td><td>Le produits de plusieurs valeurs</td>
</tr>
<tr>
<td>std()</td><td>Ladéviation standard</td>
</tr>
<tr>
<td>var()</td><td>La variance</td>
</tr>
</table>

<p>
Le résultat de toutes ces fonctions appliquées à une ligne ou à une colonne est toujours un nombre. Si une fonction est appliquée à un DataFrame ou à une sélection de lignes et de colonnes, vous pouvez spécifier si la fonction doit être appliquée aux lignes de chaque colonne (en plaçant le mot-clé <strong>axis = 0</strong> dans l'appel de la fonction), ou aux colonnes de chaque ligne (en mettant le mot-clé <strong>axis = 1</strong> dans l'appel de la fonction).
</p>

In [33]:
titanic1=titanic[['PassengerId', 'Age']]
titanic1.head()

   PassengerId   Age
0            1  22.0
1            2  38.0
2            3  26.0
3            4  35.0
4            5  35.0

In [34]:
titanic1.max(axis=0) #Verticale

PassengerId    891.0
Age             80.0
dtype: float64

In [30]:
titanic1.sum(axis=1).head()

0    23.0
1    40.0
2    29.0
3    39.0
4    40.0
dtype: float64

<p>
Notez que les fonctions citées ci-dessus sont spécifiques Pandas, et ne s'agissent pas de fonctions de Python. Il y a des différences dans leur mise en œuvre. En Python, les valeurs NaN sont prises en comptes par les opérations sans déclencher d'exception. En revanche, les opérations Pandas excluent les valeurs NaN représentant les données manquantes. Par exemple, la fonction pandas max() exclut les valeurs NaN, elles sont donc interprétées comme des valeurs manquantes, tandis que la fonction Python max() prendra NAN comme maximum :
</p>

In [62]:
print ('Fonction max de Pandas :', titanic['Age'].count())
liste = titanic['Age'].tolist()
print ('Fonction max Python  :', len(liste))

Fonction max de Pandas : 714
Fonction max Python  : 891

<p>
En plus de ces fonctions d'agrégation, nous pouvons appliquer des opérations sur toutes les valeurs des lignes, des colonnes ou une sélection des deux. La règle générale est qu'une opération sur les colonnes signifie qu'elle est appliquée à chaque ligne de cette colonne et qu'une opération sur les lignes signifie qu'elle est appliquée à chaque colonne de cette ligne. Par exemple, nous pouvons appliquer n'importe quelle opération arithmétique binaire (+, -, *, /) à une ligne ou colonne entière :
</p>

In [36]:
age = titanic['Age']
age.head()/10

0    2.2
1    3.8
2    2.6
3    3.5
4    3.5
Name: Age, dtype: float64

<p>
Nous pouvons appliquer, aussi, n'importe quelle fonction à un DataFrame ou à une série en plaçant simplement son nom comme argument de la méthode <strong>apply()</strong>. Par exemple, dans le code suivant, nous appliquons la fonction <strong>sqrt()</strong> de la bibliothèque <strong>numpy</strong> pour calculer la racine carrée de chaque valeur dans la colonne 'Value'.
</p>

In [37]:
import numpy as np
s = titanic['Age'].apply(np.sqrt)
s.head()

0    4.690416
1    6.164414
2    5.099020
3    5.916080
4    5.916080
Name: Age, dtype: float64

In [68]:
mineurs = titanic[titanic['Age']<=18]
s = mineurs['Age'].apply(round)
s.head(3)

7      2
9     14
10     4
Name: Age, dtype: int64

In [70]:
s = titanic['Name'].apply(str.upper)
s.head()

0                              BRAUND, MR. OWEN HARRIS
1    CUMINGS, MRS. JOHN BRADLEY (FLORENCE BRIGGS TH...
2                               HEIKKINEN, MISS. LAINA
3         FUTRELLE, MRS. JACQUES HEATH (LILY MAY PEEL)
4                             ALLEN, MR. WILLIAM HENRY
Name: Name, dtype: object

In [73]:
s = titanic['Sex'].map({'male': 1, 'female': 0})
print(titanic['Sex'].head(2))
print(s.head(2))

0      male
1    female
Name: Sex, dtype: object
0    1
1    0
Name: Sex, dtype: int64

<p>
Une autre manipulation de base consiste à définir de nouvelles valeurs dans notre DataFrame. Cela peut être fait directement en utilisant l'opérateur d'affectation <strong>=</strong> sur un DataFrame. Par exemple, pour ajouter une nouvelle colonne à un DataFrame, nous pouvons affecter une série à une colonne qui n'existe pas. Cela produira une nouvelle colonne dans le DataFrame après tous les autres. Vous devez être conscient que si une colonne avec le même nom existe déjà, les valeurs précédentes seront remplacées.
</p>
<p>
Dans l'exemple suivant, nous affectons la série qui résulte de la division de la colonne "Age" par la valeur maximale de la même colonne à une nouvelle colonne nommée "AgeNorm".
</p>

In [38]:
titanic['AgeNorm'] = titanic['Age'] / titanic['Age'].max()
titanic.tail()

,PassengerId,Survived,Pclass,Name,Sex,Age,SibSp,Parch,Ticket,Fare,Cabin,Embarked,AgeNorm
886,887,0,2,"Montvila, Rev. Juozas",male,27.0,0,0,211536,13.00,NaN,S,0.3375
887,888,1,1,"Graham, Miss. Margaret Edith",female,19.0,0,0,112053,30.00,B42,S,0.2375
888,889,0,3,"Johnston, Miss. Catherine Helen ""Carrie""",female,NaN,1,2,W./C. 6607,23.45,NaN,S,NaN
889,890,1,1,"Behr, Mr. Karl Howell",male,26.0,0,0,111369,30.00,C148,C,0.3250
890,891,0,3,"Dooley, Mr. Patrick",male,32.0,0,0,370376,7.75,NaN,Q,0.4000

<p>
Maintenant, si nous voulons supprimer une ligne ou colonne du DataFrame, nous pouvons utiliser la fonction <strong>drop</strong>; cela supprime les lignes indiquées si <strong>axis = 0</strong>, ou les colonnes indiquées si <strong>axis = 1</strong>.
</p>
<p>
Dans Pandas, toutes les fonctions qui modifient le contenu d'un DataFrame, comme la fonction <strong>drop</strong>, renvoient normalement une copie des données modifiées, au lieu d'écraser le DataFrame. Par conséquent, le DataFrame d'origine est conservé. Si vous ne souhaitez pas conserver les anciennes valeurs, vous pouvez définir le mot clé <strong>inplace</strong> à True. Par défaut, ce mot clé est défini à False, ce qui signifie qu'une copie des données est renvoyée.
</p>

In [39]:
ee=titanic.drop('AgeNorm', axis=1)
titanic.head()

,PassengerId,Survived,Pclass,Name,Sex,Age,SibSp,Parch,Ticket,Fare,Cabin,Embarked,AgeNorm
0,1,0,3,"Braund, Mr. Owen Harris",male,22.0,1,0,A/5 21171,7.2500,NaN,S,0.2750
1,2,1,1,"Cumings, Mrs. John Bradley (Florence Briggs Th...",female,38.0,1,0,PC 17599,71.2833,C85,C,0.4750
2,3,1,3,"Heikkinen, Miss. Laina",female,26.0,0,0,STON/O2. 3101282,7.9250,NaN,S,0.3250
3,4,1,1,"Futrelle, Mrs. Jacques Heath (Lily May Peel)",female,35.0,1,0,113803,53.1000,C123,S,0.4375
4,5,0,3,"Allen, Mr. William Henry",male,35.0,0,0,373450,8.0500,NaN,S,0.4375

In [40]:
titanic.drop('AgeNorm', axis=1, inplace=True)
titanic.head()

,PassengerId,Survived,Pclass,Name,Sex,Age,SibSp,Parch,Ticket,Fare,Cabin,Embarked
0,1,0,3,"Braund, Mr. Owen Harris",male,22.0,1,0,A/5 21171,7.2500,NaN,S
1,2,1,1,"Cumings, Mrs. John Bradley (Florence Briggs Th...",female,38.0,1,0,PC 17599,71.2833,C85,C
2,3,1,3,"Heikkinen, Miss. Laina",female,26.0,0,0,STON/O2. 3101282,7.9250,NaN,S
3,4,1,1,"Futrelle, Mrs. Jacques Heath (Lily May Peel)",female,35.0,1,0,113803,53.1000,C123,S
4,5,0,3,"Allen, Mr. William Henry",male,35.0,0,0,373450,8.0500,NaN,S

## Tri de données

<p>
Une autre fonctionnalité importante dont nous aurons besoin lors de l'inspection de nos données est de trier les données par colonnes. Nous pouvons trier un DataFrame en utilisant n'importe quelle colonne, en utilisant la fonction de tri (<strong>sort_xxxx()</strong>). Si nous voulons voir les cinq premières lignes des données triées par ordre décroissant en utilisant la colonne <strong>'Value'</strong>, alors nous pouvons écrire :
</p>

In [48]:
titanic.sort_values(by='Age', ascending=False, inplace=True)
titanic.head()

,PassengerId,Survived,Pclass,Name,Sex,Age,SibSp,Parch,Ticket,Fare,Cabin,Embarked
630,631,1,1,"Barkworth, Mr. Algernon Henry Wilson",male,80.0,0,0,27042,30.0000,A23,S
851,852,0,3,"Svensson, Mr. Johan",male,74.0,0,0,347060,7.7750,NaN,S
493,494,0,1,"Artagaveytia, Mr. Ramon",male,71.0,0,0,PC 17609,49.5042,NaN,C
96,97,0,1,"Goldschmidt, Mr. George B",male,71.0,0,0,PC 17754,34.6542,A5,C
116,117,0,3,"Connors, Mr. Patrick",male,70.5,0,0,370369,7.7500,NaN,Q

<p>
Notez que le mot-clé <strong>inplace</strong> signifie que le DataFrame sera écrasé, et donc aucun nouveau DataFrame n'est retourné. Si au lieu de <strong>ascending = False</strong>, nous utilisons <strong>ascending = True</strong>, les valeurs seront triées dans l'ordre croissant.
</p>
<p>
Si nous voulons revenir à l'ordre d'origine, nous pouvons trier par un index en utilisant la fonction <strong>sort_index</strong> et en spécifiant <strong>axis = 0</strong> :
</p>

In [49]:
titanic.sort_index(axis=0, ascending=True, inplace=True)
titanic.head()

,PassengerId,Survived,Pclass,Name,Sex,Age,SibSp,Parch,Ticket,Fare,Cabin,Embarked
0,1,0,3,"Braund, Mr. Owen Harris",male,22.0,1,0,A/5 21171,7.2500,NaN,S
1,2,1,1,"Cumings, Mrs. John Bradley (Florence Briggs Th...",female,38.0,1,0,PC 17599,71.2833,C85,C
2,3,1,3,"Heikkinen, Miss. Laina",female,26.0,0,0,STON/O2. 3101282,7.9250,NaN,S
3,4,1,1,"Futrelle, Mrs. Jacques Heath (Lily May Peel)",female,35.0,1,0,113803,53.1000,C123,S
4,5,0,3,"Allen, Mr. William Henry",male,35.0,0,0,373450,8.0500,NaN,S

## Regroupement des données

<p>
Un autre moyen très utile pour inspecter les données consiste à les regrouper selon certains critères. Par exemple, dans notre cas, il serait bien judicieux de regrouper toutes les données par pays, indépendamment de l'année. Pandas dispose de la fonction <strong>groupby</strong> qui nous permet de faire exactement cela. La valeur renvoyée par cette fonction est un DataFrame dans lequel les valeurs sont regroupés. Pour avoir un DataFrame correct, il est nécessaire d'appliquer une fonction d'agrégation (par exemple, sum(), mean, ...). Ainsi, cette fonction sera appliquée à toutes les valeurs du même groupe.
</p>
<p>
Par exemple, dans notre cas, si nous voulons un DataFrame affichant la moyenne des valeurs pour chaque pays pour toutes les années, nous pouvons l'obtenir en regroupant par pays et en utilisant la fonction <strong>mean</strong> comme méthode d'agrégation pour chaque groupe. Le résultat serait un DataFrame avec des pays comme index et les valeurs des moyennes comme colonnes :
</p>

In [50]:
group = titanic.groupby('Pclass')['Age'].mean()
group.head()

Pclass
1    38.233441
2    29.877630
3    25.140620
Name: Age, dtype: float64

In [53]:
group = titanic.groupby(['Pclass','Survived'])['Age'].mean()
group.head()

Pclass  Survived
1       0           43.695312
        1           35.368197
2       0           33.544444
        1           25.901566
3       0           26.555556
Name: Age, dtype: float64

In [ ]:
group = titanic[['Pclass', 'Age']].groupby('Age').mean()
group.head()